sonar.projectKey=wahaj-wahed_sonarqube-poc
sonar.organization=wahaj-wahed

sonar.sources=api
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.next/**,**/.git/**,**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8
