sonar.projectKey=joyboy2701_ecs-python-app-frontend
sonar.organization=joyboy2701

sonar.sources=api
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.next/**,**/.git/**,**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8
