name: Build & Push Docker Images to ECR

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-and-push:
    name: Build, Push and Deploy
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.qualitygate.wait=true